apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: axiom-operator-privileged
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "axiom-operator.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged